spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev?currentSchema=public&Unicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: postgres
    password: huawei
    driver-class-name: org.postgresql.Driver
  redis:
    host: localhost
    port: 6379
    password:
    ssl: false